language: ruby

sudo: false
cache: bundler

before_install: gem install bundler -v '~> 1.15' --conservative --minimal-deps

matrix:
  include:
    - rvm: 1.9.2
      gemfile: gemfiles/rails-3.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails-3.1.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails-3.2.gemfile
    # rails 4.x requries ruby 1.9.3 or newer
    - rvm: 1.9.3
      gemfile: gemfiles/rails-4.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails-4.1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails-4.2.gemfile
    # rails 5.x requires ruby 2.2.2+
    - rvm: 2.2.10
      gemfile: gemfiles/rails-5.0.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails-5.1.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails-5.2.gemfile
    # test latest stable rails and ruby
    - rvm: 2.6.1
      gemfile: gemfiles/rails-5.2.gemfile
